image:
  registry: ${DOCKER_REGISTRY_URL}
  tag: 1.2.0

imagePullSecrets:
  - name: ${DOCKER_REGISTRY_SECRET}

senzing:
  debug: 1
  persistentVolumeClaim: senzing-persistent-volume-claim
  subcommand: service
